sortBed -i db/roadmap/E001_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E001_snp_dist.tsv
sortBed -i db/roadmap/E002_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E002_snp_dist.tsv
sortBed -i db/roadmap/E003_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E003_snp_dist.tsv
sortBed -i db/roadmap/E004_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E004_snp_dist.tsv
sortBed -i db/roadmap/E005_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E005_snp_dist.tsv
sortBed -i db/roadmap/E006_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E006_snp_dist.tsv
sortBed -i db/roadmap/E007_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E007_snp_dist.tsv
sortBed -i db/roadmap/E008_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E008_snp_dist.tsv
sortBed -i db/roadmap/E009_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E009_snp_dist.tsv
sortBed -i db/roadmap/E010_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E010_snp_dist.tsv
sortBed -i db/roadmap/E011_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E011_snp_dist.tsv
sortBed -i db/roadmap/E012_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E012_snp_dist.tsv
sortBed -i db/roadmap/E013_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E013_snp_dist.tsv
sortBed -i db/roadmap/E014_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E014_snp_dist.tsv
sortBed -i db/roadmap/E015_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E015_snp_dist.tsv
sortBed -i db/roadmap/E016_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E016_snp_dist.tsv
sortBed -i db/roadmap/E017_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E017_snp_dist.tsv
sortBed -i db/roadmap/E018_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E018_snp_dist.tsv
sortBed -i db/roadmap/E019_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E019_snp_dist.tsv
sortBed -i db/roadmap/E020_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E020_snp_dist.tsv
sortBed -i db/roadmap/E021_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E021_snp_dist.tsv
sortBed -i db/roadmap/E022_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E022_snp_dist.tsv
sortBed -i db/roadmap/E023_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E023_snp_dist.tsv
sortBed -i db/roadmap/E024_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E024_snp_dist.tsv
sortBed -i db/roadmap/E025_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E025_snp_dist.tsv
sortBed -i db/roadmap/E026_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E026_snp_dist.tsv
sortBed -i db/roadmap/E027_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E027_snp_dist.tsv
sortBed -i db/roadmap/E028_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E028_snp_dist.tsv
sortBed -i db/roadmap/E029_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E029_snp_dist.tsv
sortBed -i db/roadmap/E030_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E030_snp_dist.tsv
sortBed -i db/roadmap/E031_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E031_snp_dist.tsv
sortBed -i db/roadmap/E032_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E032_snp_dist.tsv
sortBed -i db/roadmap/E033_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E033_snp_dist.tsv
sortBed -i db/roadmap/E034_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E034_snp_dist.tsv
sortBed -i db/roadmap/E035_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E035_snp_dist.tsv
sortBed -i db/roadmap/E036_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E036_snp_dist.tsv
sortBed -i db/roadmap/E037_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E037_snp_dist.tsv
sortBed -i db/roadmap/E038_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E038_snp_dist.tsv
sortBed -i db/roadmap/E039_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E039_snp_dist.tsv
sortBed -i db/roadmap/E040_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E040_snp_dist.tsv
sortBed -i db/roadmap/E041_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E041_snp_dist.tsv
sortBed -i db/roadmap/E042_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E042_snp_dist.tsv
sortBed -i db/roadmap/E043_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E043_snp_dist.tsv
sortBed -i db/roadmap/E044_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E044_snp_dist.tsv
sortBed -i db/roadmap/E045_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E045_snp_dist.tsv
sortBed -i db/roadmap/E046_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E046_snp_dist.tsv
sortBed -i db/roadmap/E047_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E047_snp_dist.tsv
sortBed -i db/roadmap/E048_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E048_snp_dist.tsv
sortBed -i db/roadmap/E049_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E049_snp_dist.tsv
sortBed -i db/roadmap/E050_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E050_snp_dist.tsv
sortBed -i db/roadmap/E051_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E051_snp_dist.tsv
sortBed -i db/roadmap/E052_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E052_snp_dist.tsv
sortBed -i db/roadmap/E053_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E053_snp_dist.tsv
sortBed -i db/roadmap/E054_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E054_snp_dist.tsv
sortBed -i db/roadmap/E055_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E055_snp_dist.tsv
sortBed -i db/roadmap/E056_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E056_snp_dist.tsv
sortBed -i db/roadmap/E057_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E057_snp_dist.tsv
sortBed -i db/roadmap/E058_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E058_snp_dist.tsv
sortBed -i db/roadmap/E059_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E059_snp_dist.tsv
sortBed -i db/roadmap/E061_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E061_snp_dist.tsv
sortBed -i db/roadmap/E062_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E062_snp_dist.tsv
sortBed -i db/roadmap/E063_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E063_snp_dist.tsv
sortBed -i db/roadmap/E065_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E065_snp_dist.tsv
sortBed -i db/roadmap/E066_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E066_snp_dist.tsv
sortBed -i db/roadmap/E067_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E067_snp_dist.tsv
sortBed -i db/roadmap/E068_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E068_snp_dist.tsv
sortBed -i db/roadmap/E069_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E069_snp_dist.tsv
sortBed -i db/roadmap/E070_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E070_snp_dist.tsv
sortBed -i db/roadmap/E071_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E071_snp_dist.tsv
sortBed -i db/roadmap/E072_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E072_snp_dist.tsv
sortBed -i db/roadmap/E073_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E073_snp_dist.tsv
sortBed -i db/roadmap/E074_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E074_snp_dist.tsv
sortBed -i db/roadmap/E075_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E075_snp_dist.tsv
sortBed -i db/roadmap/E076_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E076_snp_dist.tsv
sortBed -i db/roadmap/E077_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E077_snp_dist.tsv
sortBed -i db/roadmap/E078_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E078_snp_dist.tsv
sortBed -i db/roadmap/E079_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E079_snp_dist.tsv
sortBed -i db/roadmap/E080_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E080_snp_dist.tsv
sortBed -i db/roadmap/E081_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E081_snp_dist.tsv
sortBed -i db/roadmap/E082_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E082_snp_dist.tsv
sortBed -i db/roadmap/E083_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E083_snp_dist.tsv
sortBed -i db/roadmap/E084_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E084_snp_dist.tsv
sortBed -i db/roadmap/E085_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E085_snp_dist.tsv
sortBed -i db/roadmap/E086_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E086_snp_dist.tsv
sortBed -i db/roadmap/E087_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E087_snp_dist.tsv
sortBed -i db/roadmap/E088_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E088_snp_dist.tsv
sortBed -i db/roadmap/E089_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E089_snp_dist.tsv
sortBed -i db/roadmap/E090_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E090_snp_dist.tsv
sortBed -i db/roadmap/E091_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E091_snp_dist.tsv
sortBed -i db/roadmap/E092_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E092_snp_dist.tsv
sortBed -i db/roadmap/E093_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E093_snp_dist.tsv
sortBed -i db/roadmap/E094_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E094_snp_dist.tsv
sortBed -i db/roadmap/E095_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E095_snp_dist.tsv
sortBed -i db/roadmap/E096_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E096_snp_dist.tsv
sortBed -i db/roadmap/E097_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E097_snp_dist.tsv
sortBed -i db/roadmap/E098_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E098_snp_dist.tsv
sortBed -i db/roadmap/E099_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E099_snp_dist.tsv
sortBed -i db/roadmap/E100_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E100_snp_dist.tsv
sortBed -i db/roadmap/E101_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E101_snp_dist.tsv
sortBed -i db/roadmap/E102_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E102_snp_dist.tsv
sortBed -i db/roadmap/E103_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E103_snp_dist.tsv
sortBed -i db/roadmap/E104_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E104_snp_dist.tsv
sortBed -i db/roadmap/E105_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E105_snp_dist.tsv
sortBed -i db/roadmap/E106_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E106_snp_dist.tsv
sortBed -i db/roadmap/E107_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E107_snp_dist.tsv
sortBed -i db/roadmap/E108_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E108_snp_dist.tsv
sortBed -i db/roadmap/E109_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E109_snp_dist.tsv
sortBed -i db/roadmap/E110_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E110_snp_dist.tsv
sortBed -i db/roadmap/E111_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E111_snp_dist.tsv
sortBed -i db/roadmap/E112_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E112_snp_dist.tsv
sortBed -i db/roadmap/E113_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E113_snp_dist.tsv
sortBed -i db/roadmap/E114_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E114_snp_dist.tsv
sortBed -i db/roadmap/E115_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E115_snp_dist.tsv
sortBed -i db/roadmap/E116_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E116_snp_dist.tsv
sortBed -i db/roadmap/E117_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E117_snp_dist.tsv
sortBed -i db/roadmap/E118_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E118_snp_dist.tsv
sortBed -i db/roadmap/E119_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E119_snp_dist.tsv
sortBed -i db/roadmap/E120_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E120_snp_dist.tsv
sortBed -i db/roadmap/E121_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E121_snp_dist.tsv
sortBed -i db/roadmap/E122_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E122_snp_dist.tsv
sortBed -i db/roadmap/E123_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E123_snp_dist.tsv
sortBed -i db/roadmap/E124_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E124_snp_dist.tsv
sortBed -i db/roadmap/E125_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E125_snp_dist.tsv
sortBed -i db/roadmap/E126_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E126_snp_dist.tsv
sortBed -i db/roadmap/E127_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E127_snp_dist.tsv
sortBed -i db/roadmap/E128_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E128_snp_dist.tsv
sortBed -i db/roadmap/E129_25_imputed12marks_dense.bed | closestBed -d -a data/seedSNP_1817_bm.bed -b stdin > db/roadmap_dist/E129_snp_dist.tsv
