#!/usr/bin/env Rscript
# This file is for identifying T1D SNPs occupied in RoadMap enhancers

## Command Arg Parameters ##
# Rscript src/bedtools_closest_roadmap.r data/roadmap_dist.tsv
args = commandArgs(trailingOnly=T)
hmsg = 'Rscript bedtools_closest.r [bedtools_closest_result_file_path] [double_line_result]
  - Argument [bedtools_closest_result_file_path] is a mendatory file path including SNPs distance information generated by <bedtools closest> function. (data/roadmap_dist.tsv)
  - Argument [double_line_result] is an option, either "True" or "False". Default value is "True".'
if(length(args)<1|length(args)>2) stop(hmsg)
path = unlist(args[1])
if(length(args)==2) folding = unlist(args[2])

# System parameter
suppressMessages(library(data.table))
suppressMessages(library(tools))
source('src/pdtime.r')
t0 = Sys.time()
dir = 'data/'
f.name = file_path_sans_ext(basename(path))

#########################
## Function start here ##
#########################
# 1. Compiling SNP data distant from RoadMap enhancers
#rd = unlist(read.table(path,sep='\n'))
rd = as.data.frame(fread(path))
cat(paste0('>> Row number = ',dim(rd)[1],'\n'))

if(folding=='True') {
	rd.odd  = as.character(rd[c(TRUE,FALSE)])
	rd.even = as.character(rd[c(FALSE,TRUE)])
	
	gwas = as.data.frame(do.call(rbind,strsplit(rd.odd, '\t',fixed=T)))
	enh_ = as.data.frame(do.call(rbind,strsplit(rd.even,'\t',fixed=T)))[2:6]
	pos  = unlist(apply(enh_,1,function(x) paste0(x[1],':',x[2],'-',x[3])))
	enh  = cbind(pos,enh_[,4:5])

	colnames(gwas) = c('chr','start','end','rsid')
	colnames(enh)  = c('enh_pos','num','dist')
	dis = as.numeric(as.character(enh$dis))
	rd.df = cbind(gwas,enh[1:2],dis)
} else if(folding=='False') {
	pos  = unlist(apply(rd,1,function(x) paste0(x[5],':',x[6],'-',x[7])))
    rd_  = cbind(rd[1:4],pos,rd[,8:9])
    colnames(rd_) = c('chr','start','end','rsid','enh_pos','num','dist')
    dis = as.numeric(as.character(rd_$dist))
    rd.df = cbind(rd_[1:6],dis); #head(rd.df)
}


# 2. Filtering SNPs by distance of closest enhancers
rd.df_ = unique(subset(rd.df,dis==0))
cat(paste0('Enhancer occupied by SNPs = ',length(unique(rd.df_$enh_pos)),'\n'))
cat(paste0('SNPs in RoadMap enhancers = ',length(unique(rd.df_$rsid)),'\n'))
f.path1 = paste0(dir,f.name,'_df.tsv')
write.table(rd.df_,f.path1,row.names=F,quote=F,sep='\t')
cat(paste0('\nFile write: ',f.path1,'\n'))

snp.bed = unique(rd.df_[,1:4])
n1 = length(unique(snp.bed$rsid))
f.path2 = paste0(dir,'snp_',n1,'_',f.name,'.bed')
write.table(snp.bed,f.path2,row.names=F,col.names=F,quote=F,sep='\t')
cat(paste0('File write: ',f.path2,'\n'))
cat(paste0('\n>> ',pdtime(t0,1),'\n'))
##################
## Function end ##
##################